import UIKit
import SwiftBasicKit

enum ZAction: String {
    case apiupgrade = "api/upgrade"
    case apiloginpre = "api/login/pre"
    case apilogin = "api/login"
    case apilogout = "api/logout"
    case apifeedback = "api/feedback"
    case apiupload = "api/upload"
    case apisupport = "api/support"
    case apitokenlist = "api/token/list"
    case apiusertoken = "api/user/token"
    case apiuser = "api/user"
    case apiuserdetail = "api/user/detail"
    case apiuserlist = "api/user/list"
    case apiuserphotos = "api/user/photos"
    case apiuserexpends = "api/user/expends"
    case apiuseronline = "api/user/online"
    case apiuseroffline = "api/user/offline"
    case apiuserdestroy = "api/user/destroy"
    case apiuserblacklist = "api/user/black/list"
    case apiuserblock = "api/user/block"
    case apiuserunblock = "api/user/unblock"
    case apiuserreport = "api/user/report"
    case apiactivityapply = "api/activity/apply"
    case apianchorapply = "api/anchor/apply"
    case apianchordetail = "api/anchor/detail"
    case apianchorlist = "api/anchor/list"
    case apianchortake = "api/anchor/take"
    case apianchortakelist = "api/anchor/take/list"
    case apianchorfanslist = "api/anchor/fans/list"
    case apitaglist = "api/tag/list"
    case apicalllist = "api/call/list"
    case apicall = "api/call"
    case apicallhunting = "api/call/hunting"
    case apicallhuntingstop = "api/call/hunting/stop"
    case apicallanswer = "api/call/answer"
    case apicallhangup = "api/call/hangup"
    case apicallgift = "api/call/gift"
    case apicallcomment = "api/call/comment"
    case apicallcmd = "api/call/cmd"
    case apichattoken = "api/chat/token"
    case apichatmessage = "api/chat/message"
    case apichatnotify = "api/chat/notify"
    case apichatbroadcast = "api/chat/broadcast"
    case apigiftlist = "api/gift/list"
    case apipusherbind = "api/pusher/bind"
    case apipusherunbind = "api/pusher/unbind"
    case apitasklist = "api/task/list"
    case apitasktake = "api/task/take"
    case apiusercount = "api/user/count"
    case apiusermatch = "api/user/match"
    case apicallreport = "api/call/report"
    case apiuserfollow = "api/user/follow"
    case apiuserunfollow = "api/user/unfollow"
    case apiuserfollowings = "api/user/followings"
    case apiuserfollowers = "api/user/followers"
    
    var api: String { return self.rawValue }
}
